name: 'actions-bazelisk'
description: 'Download and cache bazelisk'
author: 'Suyash <hi@suy.io>'
inputs:
  token:
    description: Used to query bazelisk releases.  Since there's a default, this is typically not supplied by the user.
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
